services:
  # Container definition for the devcontainer
  devcontainer:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.14.3}
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/marty_mcfly/

networks:
  default:
    name: marty_mcfly-network
